"""Fix caption placement in LaTeX tables generated by pandoc+postprocess pipeline.

The pandoc conversion sometimes places \\caption inside \\begin{tabular},
which causes compilation errors. This script moves captions before the
tabular environment and removes longtable artifacts.
"""
import re
import logging
from rich.logging import RichHandler

logging.basicConfig(
    level=logging.INFO,
    format="%(message)s",
    handlers=[RichHandler(rich_tracebacks=True)],
)
log = logging.getLogger(__name__)

TEX_PATH = "phase4_inference/4b_partial/outputs/ANALYSIS_NOTE_4b_v1.tex"

with open(TEX_PATH, "r") as f:
    content = f.read()

# Fix 1: Move \caption{...}\label{...}\tabularnewline from inside
# \begin{tabular} to before it. This handles multi-line captions with
# nested braces (e.g., \citeproc{...}{...}).
# Strategy: find \begin{tabular}{...}\n\caption and rearrange

# Use a more flexible approach: find caption lines that end with
# \tabularnewline inside tabular environments
pattern = re.compile(
    r'(\\begin\{tabular\}\{[^}]*(?:\{[^}]*\}[^}]*)*\})\n'  # \begin{tabular}{...}
    r'(\\caption\{.*?\}\\label\{[^}]*\})\\tabularnewline',   # \caption{...}\label{...}\tabularnewline
    re.DOTALL
)

def fix_caption(match):
    tabular_begin = match.group(1)
    caption_label = match.group(2)
    return caption_label + '\n' + tabular_begin

content_fixed, n1 = pattern.subn(fix_caption, content)
log.info(f"Fix 1: Moved {n1} captions from inside tabular to before it")

# Fix 2: Remove \endfirsthead (longtable artifact in non-longtable context)
# and orphaned \bottomrule\noalign{} that follows \midrule
n_endfirsthead_before = content_fixed.count('\\endfirsthead')
content_fixed = re.sub(
    r'\\endfirsthead\n\\toprule\\noalign\{\}\n', '', content_fixed
)
content_fixed = re.sub(
    r'\\endfirsthead\n\\bottomrule\\noalign\{\}\n', '', content_fixed
)
content_fixed = re.sub(r'\\endfirsthead\n', '', content_fixed)
n_endfirsthead_after = content_fixed.count('\\endfirsthead')
log.info(f"Fix 2: Removed {n_endfirsthead_before - n_endfirsthead_after} orphaned \\endfirsthead lines")

# Fix 3: Remove \endhead (longtable artifact)
n_endhead = content_fixed.count('\\endhead')
content_fixed = content_fixed.replace('\\endhead\n', '')
log.info(f"Fix 3: Removed {n_endhead} orphaned \\endhead lines")

with open(TEX_PATH, "w") as f:
    f.write(content_fixed)

log.info(f"Saved fixed .tex to {TEX_PATH}")
